# Les infos sur le site
site_name: Numériques et Sciences Informatiques Première
site_description: Cours de NSI en classe de première du lycée Hintermann-Afféjee
site_author: Fabrice NATIVEL

# Les éléments de la barre de navigation
nav:
  - "C1-Systèmes d'exploitation" : os.md
  - "C2-Représentation des entiers et des caractères" : codage.md


#Le thème du site
theme:
  name: material
  language: fr
  # Changement de l'icone du site (dans la barre de titre) les icones sont à chercher dans ~/.local/lib/python3.8/site-packages/material/.icons
  icon:
    logo: fontawesome/solid/archway
  favicon : images/archway.svg
  # Les couleurs, on utilise la palette par défaut avec qques tweaks via css (voir https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss)
  palette: 
    scheme: default
  



markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences:          # Imbrication de blocs.
  - pymdownx.tabbed               # Volets glissants.  === "Mon volet"
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    true   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.


  - attr_list
  # Permet l'utilisation d'abbréviation dans le fichier syntaxe *[abbr]: description (voir glossaire.md)
  - abbr
  # Permet l'insertion de fichiers dans le document à l'aide de la syntaxe --8<-- "includes/glossaire.md"
  - pymdownx.snippets
  # Admonitions et variantes (details : repliable, superfences : avec onglet)
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys:
      strict: false


plugins:
  - macros
  - search

extra_css:
  - stylesheets/fenarius.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  


extra:
  icones: 
    bombe: ":fontawesome-solid-bomb:{title='Exercice difficile'}"
    histoire: ":fontawesome-solid-university:{ .histoire }"
    projet: ":fontawesome-solid-lightbulb:{ .projet }"
    typesconstruits: ":fontawesome-solid-cubes:{ .typesconstruits }"
    python: ":fontawesome-brands-python:{ .python }"
