# Les infos sur le site
site_name: Numériques et Sciences Informatiques Première
site_description: Cours de NSI en classe de première du lycée Hintermann-Afféjee
site_author: Fabrice NATIVEL

# Les éléments de la barre de navigation
nav:
  - "<img src='https://fabricenativel.github.io/NSIPremiere/images/icones/home.svg' width=16px height=16px>&thinsp; Accueil" :
    - index.md
  - "<img src='https://fabricenativel.github.io/NSIPremiere/images/icones/list-ordered-16.svg' width=16px height=16px>&thinsp; Liste des chapitres" :
      - "Progression" : progression.md
      - "C1-Systèmes d'exploitation" : os.md
      - "C2-Représentation des entiers et des caractères" : codage.md
      - "C3-Initiation à Python avec Turtle - Partie 1" : ippt1.md
      - "C4-Architecture matérielle" : architecture.md
      - "C5-Initiation à Python avec Turtle - Partie 2" : ippt2.md
      - "C6-Notions d'algorithmique" : notionsalgo.md
      - "C7-Lecture et traitement de données en table" : donneestable.md
      - "C8-Le web" : leweb.md
      - "C9-Algorithmes de tri" : algostri.md
      - "C10-Représentation des entiers négatifs" : negatifs.md
      - "C11-Réseau" : reseau.md
      - "C12-Interaction dans une page web" : interactionweb.md
      - "C13-Algorithmes gloutons" : gloutons.md
      - "C14-Fusion de tables" : fusiontable.md
      - "C15-Interface homme-machine" : interface.md
      - "C16-Notion de nombre flottant" : flottant.md
      - "C17-Algorithme des k plus proches voisins" : knn.md
  - "<img src='https://fabricenativel.github.io/NSIPremiere/images/icones/file-badge-16.svg' width=16px height=16px>&thinsp; Documents officiels" :
    - docs.md
  - "<img src='https://fabricenativel.github.io/NSIPremiere/images/icones/lightbulb.svg' width=16px height=16px>&thinsp; Projets" :
    - projets.md
  - "<img src='https://fabricenativel.github.io/NSIPremiere/images/icones/links.svg' width=16px height=16px>&thinsp; Liens" :
    - liens.md
  - "<img src='https://fabricenativel.github.io/NSIPremiere/images/icones/information.svg' width=16px height=16px>&thinsp; A propos" :
    - apropos.md



#Le thème du site
theme:
  name: material
  language: fr
  # Changement de l'icone du site (dans la barre de titre) les icones sont à chercher dans ~/.local/lib/python3.8/site-packages/material/.icons
  icon:
    logo: fontawesome/solid/dragon
  favicon : images/dragon.svg
  # Les couleurs, on utilise la palette par défaut avec qques tweaks via css (voir https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss)
  palette: 
    scheme: default
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  



markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:          # Imbrication de blocs.
  - pymdownx.tabbed:               # Volets glissants.  === "Mon volet"
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:            # Cases à cocher  - [ ]  et - [x]
        custom_checkbox:    true   #   avec cases d'origine
        clickable_checkbox: true    #   et cliquables.


  - attr_list
  # Permet l'utilisation d'abbréviation dans le fichier syntaxe *[abbr]: description (voir glossaire.md)
  - abbr
  # Admonitions et variantes (details : repliable, superfences : avec onglet)
  - admonition
  - pymdownx.details
  - pymdownx.keys:
      strict: false


plugins:
  - macros
  - search


extra_css:
  - stylesheets/fenarius.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js
  
extra:
  icones: 
    bombe: ":fontawesome-solid-bomb:{title='Exercice difficile'}"
    histoire: ":fontawesome-solid-university:{ .histoire }"
    projet: ":fontawesome-solid-lightbulb:{ .projet }"
    typesconstruits: ":fontawesome-solid-cubes:{ .typesconstruits }"
    python: ":fontawesome-brands-python:{ .python }"
